# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0c2ca7dfed433cf6750b7835fa87b5e2f379206f2ed25cb8b314d4f20c38caea2637131176417f9955558f5d3b9ab66c343442a5850e5103c275a9b686cd50d

test:
  secret_key_base: 802b644a7d74f6c09faddbfc32245f0fbf43d595eec7c3f10ff30dc43350f8cf0965255b5d69a60a49883fc1b5e3e1a1f963fcc4b4702d8e4d32b44005515b15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
